### ISSUE TITLE
Any help on this ? 

### ISSUE THREAD

**Issue by MinhajBoss** [reaitten/tgtlg#11]
```
2021-09-01T15:52:49.107078+00:00 app[aioaria2-mirror-bot.1]:   INFO     |  launch       |  Initializing bot
2021-09-01T15:52:49.130098+00:00 app[aioaria2-mirror-bot.1]:   INFO     |  bot          |  Starting
2021-09-01T15:52:49.130737+00:00 app[aioaria2-mirror-bot.1]:   INFO     |  bot          |  Loading plugins
2021-09-01T15:52:49.130847+00:00 app[aioaria2-mirror-bot.1]:   INFO     |  bot          |  Loading plugin 'Aria2' (Aria2) from '../../opt/venv/lib/python3.9/site-packages/bot/plugins/aria2.py'
2021-09-01T15:52:49.131040+00:00 app[aioaria2-mirror-bot.1]:   INFO     |  bot          |  Loading plugin 'Core' (Core) from '../../opt/venv/lib/python3.9/site-packages/bot/plugins/core.py'
2021-09-01T15:52:49.131262+00:00 app[aioaria2-mirror-bot.1]:   INFO     |  bot          |  Loading plugin 'Debug' (Debug) from '../../opt/venv/lib/python3.9/site-packages/bot/plugins/debug.py'
2021-09-01T15:52:49.131399+00:00 app[aioaria2-mirror-bot.1]:   INFO     |  bot          |  Loading plugin 'GoogleDrive' (GoogleDrive) from '../../opt/venv/lib/python3.9/site-packages/bot/plugins/gdrive.py'
2021-09-01T15:52:49.131581+00:00 app[aioaria2-mirror-bot.1]:   INFO     |  bot          |  Loading plugin 'Mega' (Mega) from '../../opt/venv/lib/python3.9/site-packages/bot/plugins/mega.py'
2021-09-01T15:52:49.131705+00:00 app[aioaria2-mirror-bot.1]:   INFO     |  bot          |  Loading plugin 'Misc' (Misc) from '../../opt/venv/lib/python3.9/site-packages/bot/plugins/misc.py'
2021-09-01T15:52:49.131793+00:00 app[aioaria2-mirror-bot.1]:   INFO     |  bot          |  All plugins loaded.
2021-09-01T15:53:19.174145+00:00 app[aioaria2-mirror-bot.1]:   ERROR    |  asyncio      |  Task exception was never retrieved
2021-09-01T15:53:19.174172+00:00 app[aioaria2-mirror-bot.1]: future: <Task finished name='Task-7' coro=<GoogleDrive.on_load() done, defined at /opt/venv/lib/python3.9/site-packages/bot/plugins/gdrive.py:76> exception=ServerSelectionTimeoutError("connection closed,connection closed,connection closed, Timeout: 30s, Topology Description: <TopologyDescription id: 612fa1d1df887f96f9dda2e0, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('cluster0-shard-00-00.b7jgw.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('connection closed')>, <ServerDescription ('cluster0-shard-00-01.b7jgw.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('connection closed')>, <ServerDescription ('cluster0-shard-00-02.b7jgw.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('connection closed')>]>")>
2021-09-01T15:53:19.174173+00:00 app[aioaria2-mirror-bot.1]: Traceback (most recent call last):
2021-09-01T15:53:19.174173+00:00 app[aioaria2-mirror-bot.1]:   File "/opt/venv/lib/python3.9/site-packages/bot/plugins/gdrive.py", line 93, in on_load
2021-09-01T15:53:19.174174+00:00 app[aioaria2-mirror-bot.1]:     credentials = (await self.db.find_one({"_id": 1})
2021-09-01T15:53:19.174174+00:00 app[aioaria2-mirror-bot.1]:   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
2021-09-01T15:53:19.174174+00:00 app[aioaria2-mirror-bot.1]:     result = self.fn(*self.args, **self.kwargs)
2021-09-01T15:53:19.174174+00:00 app[aioaria2-mirror-bot.1]:   File "/opt/venv/lib/python3.9/site-packages/pymongo/collection.py", line 1328, in find_one
2021-09-01T15:53:19.174174+00:00 app[aioaria2-mirror-bot.1]:     for result in cursor.limit(-1):
2021-09-01T15:53:19.174175+00:00 app[aioaria2-mirror-bot.1]:   File "/opt/venv/lib/python3.9/site-packages/pymongo/cursor.py", line 1238, in next
2021-09-01T15:53:19.174175+00:00 app[aioaria2-mirror-bot.1]:     if len(self.__data) or self._refresh():
2021-09-01T15:53:19.174175+00:00 app[aioaria2-mirror-bot.1]:   File "/opt/venv/lib/python3.9/site-packages/pymongo/cursor.py", line 1130, in _refresh
2021-09-01T15:53:19.174175+00:00 app[aioaria2-mirror-bot.1]:     self.__session = self.__collection.database.client._ensure_session()
2021-09-01T15:53:19.174176+00:00 app[aioaria2-mirror-bot.1]:   File "/opt/venv/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1935, in _ensure_session
2021-09-01T15:53:19.174176+00:00 app[aioaria2-mirror-bot.1]:     return self.__start_session(True, causal_consistency=False)
2021-09-01T15:53:19.174176+00:00 app[aioaria2-mirror-bot.1]:   File "/opt/venv/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1883, in __start_session
2021-09-01T15:53:19.174177+00:00 app[aioaria2-mirror-bot.1]:     server_session = self._get_server_session()
2021-09-01T15:53:19.174177+00:00 app[aioaria2-mirror-bot.1]:   File "/opt/venv/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1921, in _get_server_session
2021-09-01T15:53:19.174177+00:00 app[aioaria2-mirror-bot.1]:     return self._topology.get_server_session()
2021-09-01T15:53:19.174177+00:00 app[aioaria2-mirror-bot.1]:   File "/opt/venv/lib/python3.9/site-packages/pymongo/topology.py", line 520, in get_server_session
2021-09-01T15:53:19.174177+00:00 app[aioaria2-mirror-bot.1]:     session_timeout = self._check_session_support()
2021-09-01T15:53:19.174177+00:00 app[aioaria2-mirror-bot.1]:   File "/opt/venv/lib/python3.9/site-packages/pymongo/topology.py", line 504, in _check_session_support
2021-09-01T15:53:19.174178+00:00 app[aioaria2-mirror-bot.1]:     self._select_servers_loop(
2021-09-01T15:53:19.174178+00:00 app[aioaria2-mirror-bot.1]:   File "/opt/venv/lib/python3.9/site-packages/pymongo/topology.py", line 218, in _select_servers_loop
2021-09-01T15:53:19.174178+00:00 app[aioaria2-mirror-bot.1]:     raise ServerSelectionTimeoutError(
2021-09-01T15:53:19.174179+00:00 app[aioaria2-mirror-bot.1]: pymongo.errors.ServerSelectionTimeoutError: connection closed,connection closed,connection closed, Timeout: 30s, Topology Description: <TopologyDescription id: 612fa1d1df887f96f9dda2e0, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('cluster0-shard-00-00.b7jgw.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('connection closed')>, <ServerDescription ('cluster0-shard-00-01.b7jgw.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('connection closed')>, <ServerDescription ('cluster0-shard-00-02.b7jgw.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('connection closed')>]>
2021-09-01T15:53:54.724523+00:00 app[aioaria2-mirror-bot.1]:   INFO     |  bot          |  Stopping
2021-09-01T15:53:54.726826+00:00 app[aioaria2-mirror-bot.1]:   INFO     |  bot          |  Running post-stop hooks
2021-09-01T15:53:54.727192+00:00 app[aioaria2-mirror-bot.1]:   ERROR    |  asyncio      |  Task exception was never retrieved
2021-09-01T15:53:54.727193+00:00 app[aioaria2-mirror-bot.1]: future: <Task finished name='Task-1' coro=<run.<locals>.new_coro() done, defined at /opt/venv/lib/python3.9/site-packages/aiorun.py:221> exception=ServerSelectionTimeoutError("connection closed,connection closed,connection closed, Timeout: 30s, Topology Description: <TopologyDescription id: 612fa1d1df887f96f9dda2e0, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('cluster0-shard-00-00.b7jgw.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('connection closed')>, <ServerDescription ('cluster0-shard-00-01.b7jgw.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('connection closed')>, <ServerDescription ('cluster0-shard-00-02.b7jgw.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('connection closed')>]>")>
2021-09-01T15:53:54.727194+00:00 app[aioaria2-mirror-bot.1]: Traceback (most recent call last):
2021-09-01T15:53:54.727194+00:00 app[aioaria2-mirror-bot.1]:   File "/opt/venv/lib/python3.9/site-packages/aiorun.py", line 231, in new_coro
2021-09-01T15:53:54.727194+00:00 app[aioaria2-mirror-bot.1]:     await coro
2021-09-01T15:53:54.727195+00:00 app[aioaria2-mirror-bot.1]:   File "/opt/venv/lib/python3.9/site-packages/bot/core/bot.py", line 51, in init_and_run
2021-09-01T15:53:54.727196+00:00 app[aioaria2-mirror-bot.1]:     await bot.run()
2021-09-01T15:53:54.727196+00:00 app[aioaria2-mirror-bot.1]:   File "/opt/venv/lib/python3.9/site-packages/bot/core/telegram_bot.py", line 150, in run
2021-09-01T15:53:54.727196+00:00 app[aioaria2-mirror-bot.1]:     await self.start()
2021-09-01T15:53:54.727196+00:00 app[aioaria2-mirror-bot.1]:   File "/opt/venv/lib/python3.9/site-packages/bot/core/telegram_bot.py", line 113, in start
2021-09-01T15:53:54.727197+00:00 app[aioaria2-mirror-bot.1]:     async for user in db.find():
2021-09-01T15:53:54.727197+00:00 app[aioaria2-mirror-bot.1]:   File "/opt/venv/lib/python3.9/site-packages/motor/core.py", line 1158, in next
2021-09-01T15:53:54.727197+00:00 app[aioaria2-mirror-bot.1]:     if self.alive and (self._buffer_size() or await self._get_more()):
2021-09-01T15:53:54.727197+00:00 app[aioaria2-mirror-bot.1]:   File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
2021-09-01T15:53:54.727198+00:00 app[aioaria2-mirror-bot.1]:     result = self.fn(*self.args, **self.kwargs)
2021-09-01T15:53:54.727198+00:00 app[aioaria2-mirror-bot.1]:   File "/opt/venv/lib/python3.9/site-packages/pymongo/cursor.py", line 1130, in _refresh
2021-09-01T15:53:54.727198+00:00 app[aioaria2-mirror-bot.1]:     self.__session = self.__collection.database.client._ensure_session()
2021-09-01T15:53:54.727199+00:00 app[aioaria2-mirror-bot.1]:   File "/opt/venv/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1935, in _ensure_session
2021-09-01T15:53:54.727199+00:00 app[aioaria2-mirror-bot.1]:     return self.__start_session(True, causal_consistency=False)
2021-09-01T15:53:54.727199+00:00 app[aioaria2-mirror-bot.1]:   File "/opt/venv/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1883, in __start_session
2021-09-01T15:53:54.727199+00:00 app[aioaria2-mirror-bot.1]:     server_session = self._get_server_session()
2021-09-01T15:53:54.727200+00:00 app[aioaria2-mirror-bot.1]:   File "/opt/venv/lib/python3.9/site-packages/pymongo/mongo_client.py", line 1921, in _get_server_session
2021-09-01T15:53:54.727200+00:00 app[aioaria2-mirror-bot.1]:     return self._topology.get_server_session()
2021-09-01T15:53:54.727200+00:00 app[aioaria2-mirror-bot.1]:   File "/opt/venv/lib/python3.9/site-packages/pymongo/topology.py", line 520, in get_server_session
2021-09-01T15:53:54.727200+00:00 app[aioaria2-mirror-bot.1]:     session_timeout = self._check_session_support()
2021-09-01T15:53:54.727201+00:00 app[aioaria2-mirror-bot.1]:   File "/opt/venv/lib/python3.9/site-packages/pymongo/topology.py", line 504, in _check_session_support
2021-09-01T15:53:54.727201+00:00 app[aioaria2-mirror-bot.1]:     self._select_servers_loop(
2021-09-01T15:53:54.727201+00:00 app[aioaria2-mirror-bot.1]:   File "/opt/venv/lib/python3.9/site-packages/pymongo/topology.py", line 218, in _select_servers_loop
2021-09-01T15:53:54.727201+00:00 app[aioaria2-mirror-bot.1]:     raise ServerSelectionTimeoutError(
2021-09-01T15:53:54.727202+00:00 app[aioaria2-mirror-bot.1]: pymongo.errors.ServerSelectionTimeoutError: connection closed,connection closed,connection closed, Timeout: 30s, Topology Description: <TopologyDescription id: 612fa1d1df887f96f9dda2e0, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('cluster0-shard-00-00.b7jgw.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('connection closed')>, <ServerDescription ('cluster0-shard-00-01.b7jgw.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('connection closed')>, <ServerDescription ('cluster0-shard-00-02.b7jgw.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('connection closed')>]>
2021-09-01T15:53:55.332516+00:00 heroku[aioaria2-mirror-bot.1]: Process exited with status 0
2021-09-01T15:53:55.639678+00:00 heroku[aioaria2-mirror-bot.1]: State changed from up to crashed
```

**Comment by reaitten** [comment]
This is _not_ related to [tgtlg](github.com/reaitten/tgtlg). Ask in the mirror bot repository.
